### ISSUE TITLE
cannot install in elcipse 3.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bwebb3856/qwickie#12]
```
installing Qwickie does not work on Eclipse 3.6.1. I always get an "Artifact 
not found" error with details like this:

java.io.FileNotFoundException: 
http://qwickie.googlecode.com/svn/trunk/qwickie.updatesite/plugins/qwickie.plugi
n_0.0.5.201101231750.jar
    at org.eclipse.equinox.internal.p2.repository.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:290)

or java.io.FileNotFoundException: 
http://qwickie.googlecode.com/svn/trunk/qwickie.updatesite/features/qwickie.feat
ure_0.0.5.201101231750.jar
    at org.eclipse.equinox.internal.p2.repository.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:290)

```

Original issue reported on code.google.com by `sell.ber...@gmail.com` on 23 Jan 2011 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
dropping the downloaded jar into the plugins directory also doesnt do anything
```

Original comment by `sell.ber...@gmail.com` on 24 Jan 2011 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
Please deinstall your existing installation. The current version is 
qwickie.feature_0.0.5.201101231751.jar ending with 751 not 750. 
```

Original comment by `count.negative` on 24 Jan 2011 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
what should I deinstall?? I never had qwickie installed previously. Just 
entered the update site URL in eclipse, confirmed, waited a moment, and had the 
error dialog. Reproducible every time, from different exlipse 
installs/versions. There really isnt anything to deinstall here
```

Original comment by `sell.ber...@gmail.com` on 24 Jan 2011 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
Maybe there are some proxy settings going wrong in your environment? 
The file I cant find under 
http://qwickie.googlecode.com/svn/trunk/qwickie.updatesite/ shows version 751 
AFTER pressing Shift-F5 in my browser. But browsing the source code under 
http://code.google.com/p/qwickie/source/browse/trunk/qwickie.updatesite/site.xml
 always shows the correct version number.

Please try the urls below in your browser and check what version is shown in 
your environment. Thanks.
```

Original comment by `count.negative` on 24 Jan 2011 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
I dont know what proxy you are talking about. I am not behind any proxy that I 
know of. Yes, if I browse to the update site and look into the site.xml file, 
there is a 51 version. But when I go through the "install new software" dialog 
in eclipse (even after deleting and re-creating the site), I only see version 
"QWickie 0.0.5.201101231750". Trying to install that always gives an error.
```

Original comment by `sell.ber...@gmail.com` on 25 Jan 2011 at 7:45

**Comment by GoogleCodeExporter** [comment]
```
SOLUTION

I tried to install Qwickie on my Eclipse 3.6, and it gave me the same error 
about artifact "...750.jar" missing. Then I opened again "Install new software" 
wizard of Eclipse, entered the update site of 
Qwickie(http://qwickie.googlecode.com/svn/trunk/qwickie.updatesite/) and took a 
better look at the wizard. It only showed one artifact, version ..750. 

Then I unchecked "Show only latest versions .." and "Group Items by category" 
checkboxes of the wizard and then I saw all of the available artifacts, 
including the desired one "0.0.5....751". Then I installed it with no problems 
at all. I guess it was some sort of error in the update configuration file to 
leave "751" outside of the Qwickie main group.
```

Original comment by `damyan.m...@gmail.com` on 25 Jan 2011 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
Hm,
I even can't reproduce this behavior. Sorry, on my installation, there is only 
the     QWickie 0.0.5.201101231751 version shown. So thanks for your help 
damyan.
```

Original comment by `count.negative` on 25 Jan 2011 at 9:56
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
I had tried the "Show only latest versions .." as well, but only saw 750 and 
lower versions. Will try the "Group Items by category" option when I am home at 
my PC again.

This eclipse update/install stuff is extremely awkward IMO. Right now I am 
struggling with an issue here at work where a plugin would work well in the dev 
env., but fail to load in the exported version, showing a strange message about 
"missing host Bundle-NativeCode". It turns out that the problem was the name of 
a Windows DLL in MANIFEST.MF, where the extension was written in uppercase 
(".DLL"). Switching to lowercase did the job. Sigh..
```

Original comment by `sell.ber...@gmail.com` on 25 Jan 2011 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
I just retried here at work in an env that had never seen QWickie. Same 
results: only unchecking the "Group items by category" box will make the 751 
version appear.

It seems there is something wrong with the site configuration, probably missing 
category decl. I suggest this be fixed, as lots of people will be running into 
it..
```

Original comment by `sell.ber...@gmail.com` on 25 Jan 2011 at 10:23
