### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant qwickie.preferences.QWickiePreferencePage.SEVERITIES.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bwebb3856/qwickie#52]
```
Here's what I got in the eclipse "Error Log" view when I start Eclipse:

java.lang.IllegalArgumentException: No enum constant 
qwickie.preferences.QWickiePreferencePage.SEVERITIES.
    at java.lang.Enum.valueOf(Enum.java:236)
    at qwickie.preferences.QWickiePreferencePage$SEVERITIES.valueOf(QWickiePreferencePage.java:1)
    at qwickie.builder.QWickieBuilder.incrementalBuild(QWickieBuilder.java:442)
    at qwickie.builder.QWickieBuilder.build(QWickieBuilder.java:148)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)


I'm using the latest Qwickie plugin and Eclipse Kepler SR2 :
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.reporting.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product 
org.eclipse.epp.package.reporting.product -clean


The plugin is working without problem.


```

Original issue reported on code.google.com by `tahitian...@gmail.com` on 23 Apr 2014 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
Ok, I can reproduce this only when the property in my 
{workspace}/.metadata/.plugins/org.eclipse.core.runtime/.settings/qwickie.plugin
.prefs is empty. 

(There is a line like severity=   )

Now I'm checking this behavior on startup, but to get a workaround you can 
simply set the property via Window - Preferences - Web - QWickie - show wicket 
errors as "error".

Thanks for your report!
```

Original comment by `count.negative` on 24 Apr 2014 at 7:09
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 1.1.4
```

Original comment by `count.negative` on 25 Apr 2014 at 1:26
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
On the user interface "error" was already the selected value.
So I changed it to "warn" and set it back to "error" and now the stacktrace is 
gone.
Thank you for your help.

Going to upgrade to the latest version now.
```

Original comment by `tahitian...@gmail.com` on 25 Apr 2014 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
This bug still appear in version 1.1.7 of QWickie but can be handled by setting 
error to warn and back again. 

I am using Spring Tool Suite 3.6.1.

QWickie is a great tool!
```

Original comment by `dohrmann...@gmail.com` on 8 Sep 2014 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
That was hard to reproduce and I thought it was fixed. So thanks for kicking my 
ass.
There must be a wrong value in the qwickie.plugin.prefs file for severity. So 
it can't be valueOf'ed to a enum. In this case I've surrounded another try 
catch.
```

Original comment by `count.negative` on 9 Sep 2014 at 8:17
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
please have a look at 1.1.8
```

Original comment by `count.negative` on 9 Sep 2014 at 5:04
- Changed state: **Fixed**
