### ISSUE TITLE
(Eclipse 4.4/Luna) NPE in WicketHyperlink:236

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bwebb3856/qwickie#55]
```
I'm running the Eclipse 4.4 release version on 64-bit Linux with Oracle JDK 
1.8u5.

Clicking on the value of a <wicket:message/> tag's "key" attribute triggers the 
following exception:

java.lang.NullPointerException
    at qwickie.hyperlink.WicketHyperlink.getFilenamesToOpen(WicketHyperlink.java:236)
    at qwickie.hyperlink.WicketHyperlink.open(WicketHyperlink.java:99)
    at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseUp(HyperlinkManager.java:436)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:220)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4486)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3831)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3441)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

```

Original issue reported on code.google.com by `tr...@code-sourcery.de` on 8 Jul 2014 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
eclipse configuration
```

Original comment by `tr...@code-sourcery.de` on 8 Jul 2014 at 8:14

Attachments:
- [eclipse_configuration.txt](https://storage.googleapis.com/google-code-attachments/qwickie/issue-55/comment-2/eclipse_configuration.txt)

**Comment by GoogleCodeExporter** [comment]
```
Sorry for being overly terse: The markup I used belongs to a Page subclass and 
the resource key I clicked on is not present in the like-named .properties 
file. Previous QWickie versions would automatically add the missing resource 
key to the properties file.
```

Original comment by `tr...@code-sourcery.de` on 8 Jul 2014 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
Sorry, but I can't reproduce this. I've tested with my testproject package 
"panel" where the FieldsPanel is a subclass of AbstractFieldsPanel and in 
FieldsPanel.html there is a <wicket:message 
key="some.message"></wicket:message>. When clicking on "some.message" a file is 
created called FieldsPanel.properties an a string "some.message=" is inserted.
Maybe you could describe your project structure a bit more?
```

Original comment by `count.negative` on 13 Jul 2014 at 9:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `count.negative` on 1 Aug 2014 at 3:25
- Changed state: **Invalid**
