### ISSUE TITLE
XSD missing from JARs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bwebb3856/qwickie#59]
```

https://code.google.com/p/qwickie/source/detail?r=3ee640c460142c397e298f55d9fbb0
1216363fe7

I think you need to edit the build.properties as well to include it in the 
output JAR.

jar -tvf qwickie.plugin_1.1.10.201505151949.jar

Does not show any XSD data.  Also maybe the correct location would be inside 
META-INF/xsd/** so as not to be confused with the package 'xsd' or maybe they 
should be ok as 'qwickie/xsd/**' which is a package space for the JAR.

The following is seen in the Mars 4.5 Eclipse logs:


!ENTRY org.jboss.tools.jst.web.kb 4 0 2015-07-02 11:28:01.982
!MESSAGE JAR entry xsd/wicket-1.5.xsd not found in 
F:\Devel\eclipse-jee-mars-R-win32-x86_64\plugins\qwickie.plugin_1.1.10.201505151
949.jar
!STACK 0
java.io.FileNotFoundException: JAR entry xsd/wicket-1.5.xsd not found in 
F:\Devel\eclipse-jee-mars-R-win32-x86_64\plugins\qwickie.plugin_1.1.10.201505151
949.jar
    at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142)
    at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
    at org.jboss.tools.jst.web.kb.taglib.TagLibraryManager.convertUriToFile(TagLibraryManager.java:163)
    at org.jboss.tools.jst.web.kb.taglib.TagLibraryManager.getStaticTLD(TagLibraryManager.java:100)
    at org.jboss.tools.jst.web.kb.internal.StaticLibraries.getLibraries(StaticLibraries.java:44)
    at org.jboss.tools.jst.web.kb.internal.KbProject.getTagLibraries(KbProject.java:135)
    at org.jboss.tools.jst.web.kb.taglib.TagLibraryManager.getLibraries(TagLibraryManager.java:57)
    at org.jboss.tools.jst.web.kb.PageContextFactory.fillXMLNamespacesForNode(PageContextFactory.java:996)
    at org.jboss.tools.jst.web.kb.PageContextFactory.fillContextForNode(PageContextFactory.java:698)
    at org.jboss.tools.jst.web.kb.PageContextFactory.fillContextForChildNodes(PageContextFactory.java:687)
    at org.jboss.tools.jst.web.kb.PageContextFactory.createPageContext(PageContextFactory.java:431)
    at org.jboss.tools.jst.web.kb.PageContextFactory.createPageContext(PageContextFactory.java:236)
    at org.jboss.tools.jst.web.kb.PageContextFactory.createPageContext(PageContextFactory.java:199)
    at org.jboss.tools.jst.web.kb.PageContextFactory.createPageContext(PageContextFactory.java:184)
    at org.jboss.tools.jst.web.kb.internal.validation.ELValidator.validate(ELValidator.java:255)
    at org.jboss.tools.common.validation.AsYouTypeValidatorManager.validate(AsYouTypeValidatorManager.java:183)
    at org.jboss.tools.common.validation.AsYouTypeValidatorManager.validateString(AsYouTypeValidatorManager.java:205)
    at org.jboss.tools.common.validation.AsYouTypeValidatorManager.validateString(AsYouTypeValidatorManager.java:200)
    at org.jboss.tools.common.validation.AsYouTypeValidatorManager.validate(AsYouTypeValidatorManager.java:254)
    at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:381)
    at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:259)
    at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
    at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
    at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
    at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
    at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)


```

Original issue reported on code.google.com by `yout...@the-morg.org` on 5 Jul 2015 at 8:22

**Comment by GoogleCodeExporter** [comment]
```
Wow, thanks. I'll try to fix that.
```

Original comment by `count.negative` on 13 Jul 2015 at 8:03
- Changed state: **Accepted**
